### ISSUE TITLE
Dependencie qt5-default not available on ubuntu

### ISSUE THREAD

**Issue by Teufelchen1** [IanFinlayson/gba-tileeditor#3]
Hi!
The instruction say `sudo apt-get install qt5-default`:
- apt-get could be replaced by apt
- qt5-default it no longer shipped in Ubuntu (iirc also in recent debians)
- Instead, install: qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

**Comment by IanFinlayson** [comment]
Thanks I updated the README to install qtbase5-dev instead (which pulled the others in as dependencies).
